name = "execupresent-ai"
main = "src/index.js"             # ← ここが正しいエントリポイント

compatibility_date = "2025-04-19"

[vars]
DID_AUTH   = ""
FISH_KEY   = ""
ML_KEY     = ""
ML_SECRET  = ""

[[r2_buckets]]
binding     = "VIDEO_BUCKET"
bucket_name = "execupresent-videos"

[[d1_databases]]
binding       = "DB"
database_name = "execupresent-db"
